export const INITIAL_FAMILY_DATA = [
  // Generation 1 (Cụ tổ)
  {
    id: "g1_1",
    name: "Trần Công Gia",
    gender: "nam",
    generation: 1,
    isDeceased: true,
    birthDate: "1910-03-15",
    deathDate: "1995-10-12",
    birthPlace: "Nam Định",
    restingPlace: "Nghĩa trang dòng họ Trần Công, Vụ Bản, Nam Định",
    occupation: "Nhà nho, Thầy thuốc đông y",
    bio: "Cụ tổ khai sinh ra chi ngành. Người có công lớn trong việc giữ gìn gia quy và truyền dạy nghề bốc thuốc cứu người.",
    phone: "",
    address: "",
    spouseIds: ["g1_2"],
    fatherId: null,
    motherId: null
  },
  {
    id: "g1_2",
    name: "Lê Thị Tổ",
    gender: "nu",
    generation: 1,
    isDeceased: true,
    birthDate: "1915-05-20",
    deathDate: "1998-04-05",
    birthPlace: "Ninh Bình",
    restingPlace: "Nghĩa trang dòng họ Trần Công, Vụ Bản, Nam Định",
    occupation: "Làm nông, nội trợ",
    bio: "Cụ bà hiền hậu, tảo tần, một đời chăm lo chồng con và túc trực hỗ trợ cụ ông bốc thuốc.",
    phone: "",
    address: "",
    spouseIds: ["g1_1"],
    fatherId: null,
    motherId: null
  },

  // Generation 2
  {
    id: "g2_1",
    name: "Trần Công Trưởng",
    gender: "nam",
    generation: 2,
    isDeceased: true,
    birthDate: "1935-08-10",
    deathDate: "2018-12-25",
    birthPlace: "Nam Định",
    restingPlace: "Nghĩa trang quê nhà, Vụ Bản, Nam Định",
    occupation: "Giáo viên cấp cấp 3 (đã nghỉ hưu)",
    bio: "Con cả cụ Gia, nguyên Hiệu trưởng Trường THPT Vụ Bản. Trọn cuộc đời cống hiến cho sự nghiệp giáo dục, rất nghiêm khắc nhưng giàu lòng vị tha.",
    phone: "",
    address: "",
    spouseIds: ["g2_2"],
    fatherId: "g1_1",
    motherId: "g1_2"
  },
  {
    id: "g2_2",
    name: "Trần Thị Trưởng",
    gender: "nu",
    generation: 2,
    isDeceased: true,
    birthDate: "1940-11-12",
    deathDate: "2022-09-18",
    birthPlace: "Nam Định",
    restingPlace: "Nghĩa trang quê nhà, Vụ Bản, Nam Định",
    occupation: "Cán bộ hội phụ nữ huyện",
    bio: "Vợ cụ Trần Công Trưởng, người phụ nữ tần tảo, nuôi dạy các con thành tài trong giai đoạn chiến tranh khó khăn.",
    phone: "",
    address: "",
    spouseIds: ["g2_1"],
    fatherId: null,
    motherId: null
  },
  {
    id: "g2_3",
    name: "Trần Thị Thứ",
    gender: "nu",
    generation: 2,
    isDeceased: false,
    birthDate: "1938-04-18",
    deathDate: null,
    birthPlace: "Nam Định",
    restingPlace: "",
    occupation: "Làm nông (đã nghỉ)",
    bio: "Con thứ hai của cụ Gia. Hiện đang sinh sống cùng con trai cả tại Hà Nội. Tuy tuổi cao nhưng tinh thần vẫn rất minh mẫn, nhớ rõ lịch sử dòng họ.",
    phone: "0912345xxx",
    address: "Số 12 ngõ 45, Tây Hồ, Hà Nội",
    spouseIds: ["g2_4"],
    fatherId: "g1_1",
    motherId: "g1_2"
  },
  {
    id: "g2_4",
    name: "Vũ Văn Thứ",
    gender: "nam",
    generation: 2,
    isDeceased: true,
    birthDate: "1936-02-05",
    deathDate: "2010-07-14",
    birthPlace: "Hà Nam",
    restingPlace: "Nghĩa trang Thanh Tước, Hà Nội",
    occupation: "Sĩ quan Quân đội nhân dân Việt Nam",
    bio: "Chồng cụ Trần Thị Thứ. Từng tham gia kháng chiến chống Mỹ cứu nước, là thương binh hạng 2/4.",
    phone: "",
    address: "",
    spouseIds: ["g2_3"],
    fatherId: null,
    motherId: null
  },
  {
    id: "g2_5",
    name: "Trần Công Ba",
    gender: "nam",
    generation: 2,
    isDeceased: true,
    birthDate: "1942-09-30",
    deathDate: "2020-05-19",
    birthPlace: "Nam Định",
    restingPlace: "Công viên nghĩa trang Lạc Hồng Viên, Hòa Bình",
    occupation: "Kỹ sư Cầu đường",
    bio: "Con trai út của cụ Gia. Tính tình vui vẻ, cởi mở, có đóng góp lớn trong việc xây dựng sửa sang nhà thờ họ.",
    phone: "",
    address: "",
    spouseIds: ["g2_6"],
    fatherId: "g1_1",
    motherId: "g1_2"
  },
  {
    id: "g2_6",
    name: "Phạm Thị Ba",
    gender: "nu",
    generation: 2,
    isDeceased: false,
    birthDate: "1945-06-25",
    deathDate: null,
    birthPlace: "Thái Bình",
    restingPlace: "",
    occupation: "Bác sĩ nhi khoa (đã nghỉ hưu)",
    bio: "Vợ cụ Trần Công Ba. Hiện đang sống tại Thành phố Nam Định. Vẫn thường xuyên khám bệnh miễn phí cho trẻ em nghèo quanh vùng.",
    phone: "0909876xxx",
    address: "32 Trần Hưng Đạo, Tp. Nam Định",
    spouseIds: ["g2_5"],
    fatherId: null,
    motherId: null
  },

  // Generation 3
  {
    id: "g3_1",
    name: "Trần Công Bình",
    gender: "nam",
    generation: 3,
    isDeceased: false,
    birthDate: "1965-01-20",
    deathDate: null,
    birthPlace: "Nam Định",
    restingPlace: "",
    occupation: "Trưởng họ / Doanh nhân",
    bio: "Con trưởng cụ Trần Công Trưởng, hiện là Trưởng họ Trần Công chi này. Đang quản lý một công ty xây dựng tại Hà Nội và Nam Định, là người kết nối các hoạt động của dòng họ.",
    phone: "0913999xxx",
    address: "Biệt thự 05, KĐT Linh Đàm, Hoàng Mai, Hà Nội",
    spouseIds: ["g3_2"],
    fatherId: "g2_1",
    motherId: "g2_2"
  },
  {
    id: "g3_2",
    name: "Lê Thị Bình",
    gender: "nu",
    generation: 3,
    isDeceased: false,
    birthDate: "1968-12-05",
    deathDate: null,
    birthPlace: "Thanh Hóa",
    restingPlace: "",
    occupation: "Kế toán trưởng công ty xây dựng",
    bio: "Vợ ông Trần Công Bình. Tay hòm chìa khóa đắc lực, điều phối các quỹ khuyến học và quỹ hiếu hỷ của dòng tộc.",
    phone: "0913123xxx",
    address: "KĐT Linh Đàm, Hoàng Mai, Hà Nội",
    spouseIds: ["g3_1"],
    fatherId: null,
    motherId: null
  },
  {
    id: "g3_3",
    name: "Trần Thị Mai",
    gender: "nu",
    generation: 3,
    isDeceased: false,
    birthDate: "1968-05-14",
    deathDate: null,
    birthPlace: "Nam Định",
    restingPlace: "",
    occupation: "Giảng viên Đại học Sư phạm Hà Nội",
    bio: "Con gái cụ Trần Công Trưởng. Luôn đi đầu trong các hoạt động khuyến học của chi họ.",
    phone: "0988777xxx",
    address: "Chung cư Mandarin Garden, Cầu Giấy, Hà Nội",
    spouseIds: ["g3_4"],
    fatherId: "g2_1",
    motherId: "g2_2"
  },
  {
    id: "g3_4",
    name: "Phạm Văn Mai",
    gender: "nam",
    generation: 3,
    isDeceased: false,
    birthDate: "1965-07-28",
    deathDate: null,
    birthPlace: "Hải Dương",
    restingPlace: "",
    occupation: "Tiến sĩ Vật lý / Nghiên cứu viên",
    bio: "Chồng bà Trần Thị Mai. Đang làm việc tại Viện Hàn lâm Khoa học công nghệ Việt Nam.",
    phone: "0988999xxx",
    address: "Cầu Giấy, Hà Nội",
    spouseIds: ["g3_3"],
    fatherId: null,
    motherId: null
  },
  {
    id: "g3_5",
    name: "Vũ Quốc Khánh",
    gender: "nam",
    generation: 3,
    isDeceased: false,
    birthDate: "1962-09-10",
    deathDate: null,
    birthPlace: "Hà Nội",
    restingPlace: "",
    occupation: "Kỹ sư CNTT",
    bio: "Con trai lớn cụ Trần Thị Thứ. Là người hỗ trợ tạo dựng và quản lý các công nghệ trực tuyến cho gia tộc.",
    phone: "0903456xxx",
    address: "Số 12 ngõ 45, Tây Hồ, Hà Nội",
    spouseIds: ["g3_6"],
    fatherId: "g2_4",
    motherId: "g2_3"
  },
  {
    id: "g3_6",
    name: "Trần Thị Khánh",
    gender: "nu",
    generation: 3,
    isDeceased: false,
    birthDate: "1965-04-12",
    deathDate: null,
    birthPlace: "Hải Phòng",
    restingPlace: "",
    occupation: "Trưởng phòng Nhân sự Ngân hàng",
    bio: "Vợ ông Vũ Quốc Khánh. Chu đáo, nhiệt tình, thích tổ chức các buổi cắm trại, sum họp gia đình lớn.",
    phone: "0903789xxx",
    address: "Tây Hồ, Hà Nội",
    spouseIds: ["g3_5"],
    fatherId: null,
    motherId: null
  },
  {
    id: "g3_7",
    name: "Trần Công Hùng",
    gender: "nam",
    generation: 3,
    isDeceased: false,
    birthDate: "1970-10-15",
    deathDate: null,
    birthPlace: "Nam Định",
    restingPlace: "",
    occupation: "Bác sĩ ngoại khoa",
    bio: "Con cả cụ Trần Công Ba. Hiện là Trưởng khoa Phẫu thuật chỉnh hình tại Bệnh viện đa khoa tỉnh Nam Định.",
    phone: "0944555xxx",
    address: "Phường Vị Hoàng, Tp. Nam Định",
    spouseIds: ["g3_8"],
    fatherId: "g2_5",
    motherId: "g2_6"
  },
  {
    id: "g3_8",
    name: "Đỗ Thị Hùng",
    gender: "nu",
    generation: 3,
    isDeceased: false,
    birthDate: "1973-11-20",
    deathDate: null,
    birthPlace: "Nam Định",
    restingPlace: "",
    occupation: "Giáo viên mầm non",
    bio: "Vợ bác sĩ Hùng. Người mẹ hiền dịu, chăm sóc gia đình chu toàn và thích nấu các món ăn truyền thống Nam Định.",
    phone: "0944666xxx",
    address: "Phường Vị Hoàng, Tp. Nam Định",
    spouseIds: ["g3_7"],
    fatherId: null,
    motherId: null
  },
  {
    id: "g3_9",
    name: "Trần Công Dũng",
    gender: "nam",
    generation: 3,
    isDeceased: false,
    birthDate: "1974-03-05",
    deathDate: null,
    birthPlace: "Nam Định",
    restingPlace: "",
    occupation: "Kiến trúc sư",
    bio: "Con trai út cụ Trần Công Ba. Thiết kế nhiều công trình biệt thự, nhà thờ họ và là người yêu nghệ thuật, nhiếp ảnh.",
    phone: "0977888xxx",
    address: "Vinhomes Central Park, Bình Thạnh, Tp. Hồ Chí Minh",
    spouseIds: ["g3_10"],
    fatherId: "g2_5",
    motherId: "g2_6"
  },
  {
    id: "g3_10",
    name: "Hoàng Thị Dũng",
    gender: "nu",
    generation: 3,
    isDeceased: false,
    birthDate: "1976-08-18",
    deathDate: null,
    birthPlace: "Bến Tre",
    restingPlace: "",
    occupation: "Nhà báo",
    bio: "Vợ ông Trần Công Dũng. Làm việc tại đài truyền hình HTV, mang nét đằm thắm của con người Nam Bộ hòa hợp cùng văn hóa miền Bắc.",
    phone: "0977999xxx",
    address: "Bình Thạnh, Tp. Hồ Chí Minh",
    spouseIds: ["g3_9"],
    fatherId: null,
    motherId: null
  },

  // Generation 4
  {
    id: "g4_1",
    name: "Trần Công An",
    gender: "nam",
    generation: 4,
    isDeceased: false,
    birthDate: "1990-12-05",
    deathDate: null,
    birthPlace: "Hà Nội",
    restingPlace: "",
    occupation: "Giám đốc Dự án Công nghệ",
    bio: "Con trai cả ông Trần Công Bình (Cháu đích tôn cụ Trưởng). Làm việc tại tập đoàn công nghệ lớn, năng nổ, chịu trách nhiệm số hóa gia phả dòng họ.",
    phone: "0966111xxx",
    address: "Khu đô thị Ngoại Giao Đoàn, Bắc Từ Liêm, Hà Nội",
    spouseIds: ["g4_2"],
    fatherId: "g3_1",
    motherId: "g3_2"
  },
  {
    id: "g4_2",
    name: "Trịnh Thị An",
    gender: "nu",
    generation: 4,
    isDeceased: false,
    birthDate: "1993-02-14",
    deathDate: null,
    birthPlace: "Hà Nội",
    restingPlace: "",
    occupation: "Chuyên viên phân tích tài chính",
    bio: "Vợ anh Trần Công An. Xinh đẹp, đảm đang, rất chăm chỉ tham gia các dịp giỗ tổ họ hàng.",
    phone: "0966222xxx",
    address: "Bắc Từ Liêm, Hà Nội",
    spouseIds: ["g4_1"],
    fatherId: null,
    motherId: null
  },
  {
    id: "g4_3",
    name: "Trần Thị Chi",
    gender: "nu",
    generation: 4,
    isDeceased: false,
    birthDate: "1995-07-22",
    deathDate: null,
    birthPlace: "Hà Nội",
    restingPlace: "",
    occupation: "Nhà thiết kế thời trang",
    bio: "Con gái ông Trần Công Bình. Tốt nghiệp du học Pháp, hiện làm chủ một thương hiệu thời trang tại Hà Nội.",
    phone: "0966333xxx",
    address: "Phố cổ Hoàn Kiếm, Hà Nội",
    spouseIds: ["g4_4"],
    fatherId: "g3_1",
    motherId: "g3_2"
  },
  {
    id: "g4_4",
    name: "Bùi Văn Chi",
    gender: "nam",
    generation: 4,
    isDeceased: false,
    birthDate: "1992-05-18",
    deathDate: null,
    birthPlace: "Hải Phòng",
    restingPlace: "",
    occupation: "Luật sư",
    bio: "Chồng chị Trần Thị Chi. Tư vấn pháp lý doanh nghiệp, năng nổ, thường hỗ trợ pháp lý và tài chính cho các hoạt động xã hội.",
    phone: "0966444xxx",
    address: "Hoàn Kiếm, Hà Nội",
    spouseIds: ["g4_3"],
    fatherId: null,
    motherId: null
  },
  {
    id: "g4_5",
    name: "Trần Thị Lan",
    gender: "nu",
    generation: 4,
    isDeceased: false,
    birthDate: "1998-10-30",
    deathDate: null,
    birthPlace: "Nam Định",
    restingPlace: "",
    occupation: "Dược sĩ lâm sàng",
    bio: "Con gái ông Trần Công Hùng. Tiếp nối truyền thống y đức của dòng họ, tốt nghiệp loại Giỏi Đại học Y Dược.",
    phone: "0944111xxx",
    address: "Phường Vị Hoàng, Tp. Nam Định",
    spouseIds: [],
    fatherId: "g3_7",
    motherId: "g3_8"
  },
  {
    id: "g4_6",
    name: "Trần Công Nam",
    gender: "nam",
    generation: 4,
    isDeceased: false,
    birthDate: "2002-04-15",
    deathDate: null,
    birthPlace: "Nam Định",
    restingPlace: "",
    occupation: "Sinh viên Đại học Bách Khoa",
    bio: "Con trai thứ ông Trần Công Hùng. Đam mê robot, lập trình viên trẻ triển vọng.",
    phone: "0944222xxx",
    address: "Ký túc xá Đại học Bách Khoa, Hà Nội",
    spouseIds: [],
    fatherId: "g3_7",
    motherId: "g3_8"
  },
  {
    id: "g4_7",
    name: "Trần Công Hải",
    gender: "nam",
    generation: 4,
    isDeceased: false,
    birthDate: "2005-09-08",
    deathDate: null,
    birthPlace: "Tp. Hồ Chí Minh",
    restingPlace: "",
    occupation: "Học sinh THPT chuyên Lê Hồng Phong",
    bio: "Con trai duy nhất của ông Trần Công Dũng. Yêu thích hội họa giống bố, đạt giải cấp thành phố môn tiếng Anh.",
    phone: "0977111xxx",
    address: "Bình Thạnh, Tp. Hồ Chí Minh",
    spouseIds: [],
    fatherId: "g3_9",
    motherId: "g3_10"
  },

  // Generation 5
  {
    id: "g5_1",
    name: "Trần Công Minh",
    gender: "nam",
    generation: 5,
    isDeceased: false,
    birthDate: "2018-09-28",
    deathDate: null,
    birthPlace: "Hà Nội",
    restingPlace: "",
    occupation: "Học sinh tiểu học",
    bio: "Con cả anh Trần Công An. Cậu bé thông minh tinh nghịch, rất thích vẽ tranh và lắp ráp Lego.",
    phone: "",
    address: "",
    spouseIds: [],
    fatherId: "g4_1",
    motherId: "g4_2"
  },
  {
    id: "g5_2",
    name: "Trần Ngọc Vy",
    gender: "nu",
    generation: 5,
    isDeceased: false,
    birthDate: "2021-12-14",
    deathDate: null,
    birthPlace: "Hà Nội",
    restingPlace: "",
    occupation: "Đi học mẫu giáo",
    bio: "Con gái nhỏ anh Trần Công An. Bé Vy lém lỉnh, thích ca hát và múa, là niềm vui lớn của cả gia đình.",
    phone: "",
    address: "",
    spouseIds: [],
    fatherId: "g4_1",
    motherId: "g4_2"
  }
];

export const getAge = (birthDate, deathDate, isDeceased) => {
  if (!birthDate) return null;
  const birth = new Date(birthDate);
  const end = isDeceased && deathDate ? new Date(deathDate) : new Date();
  
  let age = end.getFullYear() - birth.getFullYear();
  const m = end.getMonth() - birth.getMonth();
  if (m < 0 || (m === 0 && end.getDate() < birth.getDate())) {
    age--;
  }
  return age;
};

export const getGenderLabel = (gender) => {
  return gender === "nam" ? "Nam" : "Nữ";
};
