export const INITIAL_FAMILY_DATA = [
  // Generation 1 (Thủy tổ)
  {
    id: "g1_1",
    name: "Trần Công Kỳ",
    gender: "nam",
    generation: 1,
    isDeceased: true,
    birthDate: null,
    deathDate: "1936-06-04",
    birthPlace: "",
    restingPlace: "",
    occupation: "Thủy tổ chi ngành",
    bio: "Tạ thế ngày 4-6-1936. Có 5 người con (2 trai, 3 gái).",
    phone: "",
    address: "",
    spouseIds: ["g1_2"],
    fatherId: null,
    motherId: null
  },
  {
    id: "g1_2",
    name: "Trần Thị Hiền",
    gender: "nu",
    generation: 1,
    isDeceased: true,
    birthDate: null,
    deathDate: "1959-03-20",
    birthPlace: "",
    restingPlace: "",
    occupation: "Matriarch",
    bio: "Tạ thế ngày 20-3-1959.",
    phone: "",
    address: "",
    spouseIds: ["g1_1"],
    fatherId: null,
    motherId: null
  },

  // Generation 2
  {
    id: "g2_1",
    name: "Trần Thị Mùi",
    gender: "nu",
    generation: 2,
    isDeceased: true,
    birthDate: null,
    deathDate: null,
    birthPlace: "",
    restingPlace: "",
    occupation: "",
    bio: "Có 5 người con.",
    phone: "",
    address: "",
    spouseIds: ["g2_2"],
    fatherId: "g1_1",
    motherId: "g1_2"
  },
  {
    id: "g2_2",
    name: "Trần Sỹ Pha",
    gender: "nam",
    generation: 2,
    isDeceased: true,
    birthDate: null,
    deathDate: null,
    birthPlace: "Làng Mai",
    restingPlace: "",
    occupation: "",
    bio: "Chồng cụ Trần Thị Mùi.",
    phone: "",
    address: "",
    spouseIds: ["g2_1"],
    fatherId: null,
    motherId: null
  },
  {
    id: "g2_3",
    name: "Trần Thị Sên",
    gender: "nu",
    generation: 2,
    isDeceased: true,
    birthDate: null,
    deathDate: null,
    birthPlace: "",
    restingPlace: "",
    occupation: "",
    bio: "Có 2 người con gái.",
    phone: "",
    address: "",
    spouseIds: ["g2_4"],
    fatherId: "g1_1",
    motherId: "g1_2"
  },
  {
    id: "g2_4",
    name: "Trần Đình Bảng",
    gender: "nam",
    generation: 2,
    isDeceased: true,
    birthDate: null,
    deathDate: null,
    birthPlace: "Cùng làng",
    restingPlace: "",
    occupation: "",
    bio: "Chồng cụ Trần Thị Sên.",
    phone: "",
    address: "",
    spouseIds: ["g2_3"],
    fatherId: null,
    motherId: null
  },
  {
    id: "g2_5",
    name: "Trần Công Nghiêm",
    gender: "nam",
    generation: 2,
    isDeceased: true,
    birthDate: null,
    deathDate: "1980-02-02",
    birthPlace: "",
    restingPlace: "",
    occupation: "",
    bio: "Tạ thế ngày 2-2-1980. Có 3 con trai và 4 con gái.",
    phone: "",
    address: "",
    spouseIds: ["g2_6"],
    fatherId: "g1_1",
    motherId: "g1_2"
  },
  {
    id: "g2_6",
    name: "Trần Thị Viết",
    gender: "nu",
    generation: 2,
    isDeceased: true,
    birthDate: null,
    deathDate: null,
    birthPlace: "",
    restingPlace: "",
    occupation: "",
    bio: "Vợ cụ Trần Công Nghiêm.",
    phone: "",
    address: "",
    spouseIds: ["g2_5"],
    fatherId: null,
    motherId: null
  },
  {
    id: "g2_7",
    name: "Trần Thị Kỷ",
    gender: "nu",
    generation: 2,
    isDeceased: true,
    birthDate: null,
    deathDate: null,
    birthPlace: "",
    restingPlace: "",
    occupation: "",
    bio: "Có 6 người con (2 trai, 4 gái).",
    phone: "",
    address: "",
    spouseIds: ["g2_8"],
    fatherId: "g1_1",
    motherId: "g1_2"
  },
  {
    id: "g2_8",
    name: "Đặng Hữu Liên",
    gender: "nam",
    generation: 2,
    isDeceased: true,
    birthDate: null,
    deathDate: null,
    birthPlace: "Làng Mỹ",
    restingPlace: "",
    occupation: "",
    bio: "Chồng cụ Trần Thị Kỷ.",
    phone: "",
    address: "",
    spouseIds: ["g2_7"],
    fatherId: null,
    motherId: null
  },
  {
    id: "g2_9",
    name: "Trần Công Kỷ",
    gender: "nam",
    generation: 2,
    isDeceased: true,
    birthDate: null,
    deathDate: null,
    birthPlace: "",
    restingPlace: "",
    occupation: "",
    bio: "Có 2 người con (1 trai, 1 gái).",
    phone: "",
    address: "",
    spouseIds: ["g2_10"],
    fatherId: "g1_1",
    motherId: "g1_2"
  },
  {
    id: "g2_10",
    name: "Nguyễn Thị Khoa",
    gender: "nu",
    generation: 2,
    isDeceased: true,
    birthDate: null,
    deathDate: null,
    birthPlace: "",
    restingPlace: "",
    occupation: "",
    bio: "Vợ cụ Trần Công Kỷ.",
    phone: "",
    address: "",
    spouseIds: ["g2_9"],
    fatherId: null,
    motherId: null
  },

  // Generation 3 (Children of Trần Công Nghiêm)
  {
    id: "g3_1",
    name: "Trần Thị Tý",
    gender: "nu",
    generation: 3,
    isDeceased: true,
    birthDate: "1928-01-01",
    deathDate: null,
    birthPlace: "",
    restingPlace: "",
    occupation: "",
    bio: "Sinh năm 1928. Có 3 trai và 1 gái.",
    phone: "",
    address: "",
    spouseIds: ["g3_2"],
    fatherId: "g2_5",
    motherId: "g2_6"
  },
  {
    id: "g3_2",
    name: "Trần Văn Tiềm",
    gender: "nam",
    generation: 3,
    isDeceased: true,
    birthDate: null,
    deathDate: null,
    birthPlace: "",
    restingPlace: "",
    occupation: "",
    bio: "Chồng bà Trần Thị Tý.",
    phone: "",
    address: "",
    spouseIds: ["g3_1"],
    fatherId: null,
    motherId: null
  },
  {
    id: "g3_3",
    name: "Trần Thị Vàng",
    gender: "nu",
    generation: 3,
    isDeceased: true,
    birthDate: "1930-01-01",
    deathDate: "1959-03-02",
    birthPlace: "",
    restingPlace: "",
    occupation: "",
    bio: "Sinh năm 1930. Tạ thế ngày 2-3-1959. Chưa chồng (Nhận 1 con gái).",
    phone: "",
    address: "",
    spouseIds: [],
    fatherId: "g2_5",
    motherId: "g2_6"
  },
  {
    id: "g3_4",
    name: "Trần Thị Hường",
    gender: "nu",
    generation: 3,
    isDeceased: true,
    birthDate: "1932-01-01",
    deathDate: null,
    birthPlace: "",
    restingPlace: "",
    occupation: "",
    bio: "Sinh năm 1932. Có 4 người con (3 trai, 1 gái).",
    phone: "",
    address: "",
    spouseIds: ["g3_5"],
    fatherId: "g2_5",
    motherId: "g2_6"
  },
  {
    id: "g3_5",
    name: "Trần Văn Lễ",
    gender: "nam",
    generation: 3,
    isDeceased: true,
    birthDate: null,
    deathDate: null,
    birthPlace: "",
    restingPlace: "",
    occupation: "",
    bio: "Chồng bà Trần Thị Hường.",
    phone: "",
    address: "",
    spouseIds: ["g3_4"],
    fatherId: null,
    motherId: null
  },
  {
    id: "g3_6",
    name: "Trần Thị Oan",
    gender: "nu",
    generation: 3,
    isDeceased: true,
    birthDate: "1935-01-01",
    deathDate: null,
    birthPlace: "",
    restingPlace: "",
    occupation: "",
    bio: "Sinh năm 1935. Có 4 người con (3 trai, 1 gái).",
    phone: "",
    address: "",
    spouseIds: ["g3_7"],
    fatherId: "g2_5",
    motherId: "g2_6"
  },
  {
    id: "g3_7",
    name: "Trần Nhật Chước",
    gender: "nam",
    generation: 3,
    isDeceased: true,
    birthDate: null,
    deathDate: null,
    birthPlace: "",
    restingPlace: "",
    occupation: "",
    bio: "Chồng bà Trần Thị Oan.",
    phone: "",
    address: "",
    spouseIds: ["g3_6"],
    fatherId: null,
    motherId: null
  },
  {
    id: "g3_8",
    name: "Trần Công Huê",
    gender: "nam",
    generation: 3,
    isDeceased: true,
    birthDate: "1938-01-01",
    deathDate: "1992-05-21",
    birthPlace: "",
    restingPlace: "",
    occupation: "",
    bio: "Sinh năm 1938. Tạ thế ngày 21-5-1992. Có 3 người con (1 trai, 2 gái).",
    phone: "",
    address: "",
    spouseIds: ["g3_9"],
    fatherId: "g2_5",
    motherId: "g2_6"
  },
  {
    id: "g3_9",
    name: "Trần Thị Thức",
    gender: "nu",
    generation: 3,
    isDeceased: true,
    birthDate: null,
    deathDate: null,
    birthPlace: "",
    restingPlace: "",
    occupation: "",
    bio: "Vợ ông Trần Công Huê.",
    phone: "",
    address: "",
    spouseIds: ["g3_8"],
    fatherId: null,
    motherId: null
  },
  {
    id: "g3_10",
    name: "Trần Công Bảy",
    gender: "nam",
    generation: 3,
    isDeceased: true,
    birthDate: "1941-01-01",
    deathDate: null,
    birthPlace: "",
    restingPlace: "",
    occupation: "",
    bio: "Sinh năm 1941. Có 5 người con (3 trai, 2 gái).",
    phone: "",
    address: "",
    spouseIds: ["g3_11"],
    fatherId: "g2_5",
    motherId: "g2_6"
  },
  {
    id: "g3_11",
    name: "Trần Thị Thực",
    gender: "nu",
    generation: 3,
    isDeceased: true,
    birthDate: null,
    deathDate: null,
    birthPlace: "",
    restingPlace: "",
    occupation: "",
    bio: "Vợ ông Trần Công Bảy.",
    phone: "",
    address: "",
    spouseIds: ["g3_10"],
    fatherId: null,
    motherId: null
  },
  {
    id: "g3_12",
    name: "Trần Công Tám",
    gender: "nam",
    generation: 3,
    isDeceased: false,
    birthDate: "1944-01-01",
    deathDate: null,
    birthPlace: "",
    restingPlace: "",
    occupation: "",
    bio: "Sinh năm 1944. Có 3 người con (1 trai, 2 gái).",
    phone: "",
    address: "",
    spouseIds: ["g3_13"],
    fatherId: "g2_5",
    motherId: "g2_6"
  },
  {
    id: "g3_13",
    name: "Vợ Trần Công Tám",
    gender: "nu",
    generation: 3,
    isDeceased: false,
    birthDate: null,
    deathDate: null,
    birthPlace: "",
    restingPlace: "",
    occupation: "",
    bio: "Vợ ông Trần Công Tám.",
    phone: "",
    address: "",
    spouseIds: ["g3_12"],
    fatherId: null,
    motherId: null
  },

  // Generation 3 (Children of Trần Công Kỷ)
  {
    id: "g3_14",
    name: "Trần Thị Hoa",
    gender: "nu",
    generation: 3,
    isDeceased: true,
    birthDate: "1932-01-01",
    deathDate: null,
    birthPlace: "",
    restingPlace: "",
    occupation: "",
    bio: "Sinh năm 1932. Có 5 người con (4 trai, 1 gái).",
    phone: "",
    address: "",
    spouseIds: ["g3_15"],
    fatherId: "g2_9",
    motherId: "g2_10"
  },
  {
    id: "g3_15",
    name: "Trần Văn Tăng",
    gender: "nam",
    generation: 3,
    isDeceased: true,
    birthDate: null,
    deathDate: null,
    birthPlace: "",
    restingPlace: "",
    occupation: "",
    bio: "Chồng bà Trần Thị Hoa.",
    phone: "",
    address: "",
    spouseIds: ["g3_14"],
    fatherId: null,
    motherId: null
  },
  {
    id: "g3_16",
    name: "Trần Thị Xuân",
    gender: "nu",
    generation: 3,
    isDeceased: true,
    birthDate: "1935-01-01",
    deathDate: null,
    birthPlace: "",
    restingPlace: "",
    occupation: "",
    bio: "Sinh năm 1935. Có 3 người con (1 trai, 2 gái).",
    phone: "",
    address: "",
    spouseIds: ["g3_17"],
    fatherId: "g2_9",
    motherId: "g2_10"
  },
  {
    id: "g3_17",
    name: "Trần Văn Thắng",
    gender: "nam",
    generation: 3,
    isDeceased: true,
    birthDate: null,
    deathDate: null,
    birthPlace: "",
    restingPlace: "",
    occupation: "",
    bio: "Chồng bà Trần Thị Xuân.",
    phone: "",
    address: "",
    spouseIds: ["g3_16"],
    fatherId: null,
    motherId: null
  },
  {
    id: "g3_18",
    name: "Trần Công Mợi",
    gender: "nam",
    generation: 3,
    isDeceased: true,
    birthDate: "1937-01-01",
    deathDate: null,
    birthPlace: "",
    restingPlace: "",
    occupation: "",
    bio: "Sinh năm 1937. Có 8 người con (3 trai, 5 gái).",
    phone: "",
    address: "",
    spouseIds: ["g3_19"],
    fatherId: "g2_9",
    motherId: "g2_10"
  },
  {
    id: "g3_19",
    name: "Vợ Trần Công Mợi",
    gender: "nu",
    generation: 3,
    isDeceased: true,
    birthDate: null,
    deathDate: null,
    birthPlace: "",
    restingPlace: "",
    occupation: "",
    bio: "Vợ ông Trần Công Mợi.",
    phone: "",
    address: "",
    spouseIds: ["g3_18"],
    fatherId: null,
    motherId: null
  }
];

export const getAge = (birthDate, deathDate, isDeceased) => {
  if (!birthDate) return null;
  const birth = new Date(birthDate);
  const end = isDeceased && deathDate ? new Date(deathDate) : new Date();
  
  let age = end.getFullYear() - birth.getFullYear();
  const m = end.getMonth() - birth.getMonth();
  if (m < 0 || (m === 0 && end.getDate() < birth.getDate())) {
    age--;
  }
  return age;
};

export const getGenderLabel = (gender) => {
  return gender === "nam" ? "Nam" : "Nữ";
};
